//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BasteleiApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class measurements
    {
        public int id { get; set; }
        public int probe_id { get; set; }
        public System.DateTime time { get; set; }
        public string datatype { get; set; }
        public float value { get; set; }
    }
}
