//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BasteleiApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Probe
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Probe()
        {
            this.Measurement = new HashSet<Measurement>();
        }
    
        public int id { get; set; }
        public int user_id { get; set; }
        public string token { get; set; }
        public string locationname { get; set; }
        public string location { get; set; }
        public bool verified { get; set; }
        public string comment { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Measurement> Measurement { get; set; }
        public virtual User User { get; set; }
    }
}
